### ISSUE TITLE
Functionality request: Specific terminal.

### ISSUE THREAD

**Issue by altair984** [TaureHorn/FoundryVTT_ChatConsole#11]
Hello, first of all thank you for your module I love it, in fact I like it so much, I would like, if possible the fact of adding the following functionality, as it would be perfect for me. 

Could it be possible to add a new option where you can generate a terminal which is only visible to a single player and not for all? as a personal chat or email and that could not see the other players. 

Thanks for everything :)

**Comment by TaureHorn** [comment]
Done. Update to release v.1.4.0 and you should be able to do what you've asked for alongside some other things :)

**Comment by altair984** [comment]
thanks so much
