### ISSUE TITLE
Console dont work

### ISSUE THREAD

**Issue by altair984** [TaureHorn/FoundryVTT_ChatConsole#14]
![image](https://github.com/TaureHorn/FoundryVTT_ChatConsole/assets/52784850/22a7988b-6895-4ca4-bd0f-b99df9a200e6)

cant save the terminal or console :(

    // Trigger the object update
    try {
      await this._updateObject(event, formData);
    }
    catch(err) {
      console.error(err);
      closeForm = false;
      this._state = priorState;
    }

    // Restore flags and optionally close the form
    this._submitting = false;
    if ( preventRender ) this._state = priorState;
    if ( closeForm ) await this.close({submit: false, force: true});
    return formData;
  }

**Comment by TaureHorn** [comment]
Nice catch. Not an edge case I had considered.
Update to v.1.4.1 and it should be fine.

**Comment by altair984** [comment]
at moment work fine, thanks :)
