### ISSUE TITLE
FUNCTIONALITY REQUEST: Add the console window to chat

### ISSUE THREAD

**Issue by kay-hk** [TaureHorn/FoundryVTT_ChatConsole#19]
Hello there! A lovely module, thank you very much for creating it. I do, however, have a small request. 

Would it be able to force-pin the created console? So that it remains open for all players.

One of our players prefers to write than speak, so this console is perfect for them, but many players forget the console exist, and miss his lines. 

Thank you in advance!

**Comment by TaureHorn** [comment]
Sorry. I'm not entirely sure I understand what you're asking for. Do you want to for a console window to not close when a user hits the Esc key and closes all the open windows? Or are you asking for the console to be part of the sidebar and not its own popped out window?

**Comment by kay-hk** [comment]
Apologies if what I wrote is not very clear; yes, I suppose I want to have the console stay open when ESC is pressed. 

Being able to add the console to the sidebar could also be a solution!

 I just don't want my players to be able to close it manually if I, as GM, want them to keep it open. I don't know if this would be possible, but thank you!

**Comment by TaureHorn** [comment]
PR #20 should achieve roughly what you were after. It doesn't give you complete and total control of whether or not the window remains open on a players screen, nor do I think its a good idea to have that unilateral power. But, it gives you a lot more control than before, especially if you set the config to be anchored by default.

It might be another day or two until I push a new release that you can update inside Foundry to. You can pull from main to your foundry modules folder to test it out before then if you like though.
