### ISSUE TITLE
v12 Compatibility

### ISSUE THREAD

**Issue by Stexinator** [TaureHorn/FoundryVTT_ChatConsole#38]
Is it planned to bring this to v12? As far as I used it there where no problems with v12

**Comment by TaureHorn** [comment]
It already is in v12. Latest release v1.6.2 is verified for foundry v12.327.

If you have any experiences with bugs, please submit an issue.

**Comment by Stexinator** [comment]
Maybe something went wrong then. While I can install it in v12 it is not verified

https://github.com/TaureHorn/FoundryVTT_ChatConsole/blob/main/module.json shows 11.315

**Comment by TaureHorn** [comment]
Good spot. I've changed the verified version in the module.json. See if that allows you to install it now.
