### ISSUE TITLE
Incognito throws error

### ISSUE THREAD

**Issue by Stexinator** [TaureHorn/FoundryVTT_ChatConsole#39]
Uncaught TypeError: this._element is null
[Detected 1 package: console(1.6.2)]
    updateAppClasses /modules/console/classes/consoleApp.js:292

**Comment by TaureHorn** [comment]
I'm going to need a little more context for your issue. What were you doing when this error arose? What happened? What were you expecting to happen? Foundry version? Browser? That sort of thing.

**Comment by TaureHorn** [comment]
commit ff07725a21486d17d3910bdf2a544f9d438bc2b6 fixed these errors.

I don't see that these errors were actually breaking anything or impacting functionality so I won't be pushing a new release for a bit. It'll be incorporated in a new release soon-ish when I've completed some other small additions.
