### ISSUE TITLE
I can't update

### ISSUE THREAD

**Issue by brunocalado** [TaureHorn/FoundryVTT_ChatConsole#4]
I can't update the module
![image](https://github.com/TaureHorn/FoundryVTT_ChatConsole/assets/4999783/fbfc0ecb-c09e-475f-86bc-c69f6e32ac34)

**Comment by TaureHorn** [comment]
I messed up the `module.json` file in the earlier releases. It should be fixed now. You'll have to uninstall and reinstall though.
