### ISSUE TITLE
Feature: Default Settings - Color

### ISSUE THREAD

**Issue by Stexinator** [TaureHorn/FoundryVTT_ChatConsole#40]
I dont want to re-set the colors everytime I create a new console. I would be fine if it would remember the last config

**Comment by TaureHorn** [comment]
I can add a default colors selector in the module settings menu.

**Comment by TaureHorn** [comment]
023467d0b35787844d46c483ab88a1aea9477068 added the ability to set a default background and foreground color.

Not super happy with this implementation, but I have some ideas how to improve and extend this functionality. Leaving thread open til I implement those changes.

**Comment by TaureHorn** [comment]
[release v1.6.3] added the ability to define a default config for any newly created consoles. Default config menu is accessed through the modules settings.
