### ISSUE TITLE
Lack of permission to update journalentry

### ISSUE THREAD

**Issue by evilTheVIOLATOR** [TaureHorn/FoundryVTT_ChatConsole#41]
Hello,
just try your module and i think is amazing. 
Occour an error when a player try to use the chat (i set the ownership) but Foundry send me this error: user xxxx Lack of permission to update journalentry.
How i can fix it?

Thank you!

**Comment by TaureHorn** [comment]
Did you give the player ownership over the 'console-data' journal entry as well as permission to view the specific console?

**Comment by TaureHorn** [comment]
I've added 7935b536fc10d838ca3c3cf079debcfea9c2fc2d which means in the future, the "_console-data" journal entry that stores the modules data will have **all players as owners by default**.

**Comment by TaureHorn** [comment]
As of [v1.6.3](https://github.com/TaureHorn/FoundryVTT_ChatConsole/releases/tag/v1.6.3) is owned by all players by default.
