### ISSUE TITLE
Too Many Scenes

### ISSUE THREAD

**Issue by brunocalado** [TaureHorn/FoundryVTT_ChatConsole#9]
Hi. Great module! Thank you.

I have too many scenes on my world and this makes messy to use your module. Is scenes really necessary? Why are they show in options? If so can you make easier to deal with many scenes? 

Thank you

https://github.com/TaureHorn/FoundryVTT_ChatConsole/assets/4999783/1b90797b-2d25-47eb-ac7e-957df6b6a6ec

**Comment by TaureHorn** [comment]
#10  I've limited the size that the scenes list can show on screen and also just made the config menu a little more compact.
Update to v1.3.1 and you should be fine.

Also, you have soooo many scenes, you have a problem, this is an intervention :))
